[tool.poetry]
name = "french-cities"
version = "1.1.4"
description = "Toolbox on french cities: set vintage, find departments, find cities..."
authors = ["thomas.grandjean <thomas.grandjean@developpement-durable.gouv.fr>"]
license = "GPL-3.0-or-later"
readme = ["README.md"]
homepage = "https://github.com/tgrandje/french-cities/"
repository = "https://github.com/tgrandje/french-cities/"
documentation = "https://tgrandje.github.io/french-cities/"
keywords = ["france", "cities"]
packages = [{include = "french_cities"}]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/tgrandje/french-cities/issues"

[tool.poetry.dependencies]
python = "^3.11"
requests-cache = "^1"
unidecode = "^1"
python-dotenv = "^1"
pandas = "^2"
geopandas = "^1"
rapidfuzz = "^3"
pebble = "^5"
tqdm = "^4"
importlib-metadata = "^9"
geopy = "^2"
diskcache = "^5"
platformdirs = "^4"
setuptools = "^83"
pynsee = "^0"

[tool.poetry.group.dev.dependencies]
spyder = "^6"
pytest = "^9"
licensecheck = "^2025"
pyqt5-qt5 = "5.15.2"
pyqtwebengine-qt5 = "5.15.2"
lxml = "^6"
openpyxl = "^3"
matplotlib = "^3"
seaborn = "^0"
vulture = "^2"
pytest-cov = "^7"
genbadge = {extras = ["all"], version = "^1"}
flake8 = "^7"
pre-commit = "^4"
black = "^26"
ipywidgets = "^8"
jupyter = "^1"


[tool.pytest.ini_options]
log_cli = true
log_cli_level = "WARNING"
log_format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
addopts = "--cov-report xml:./reports/coverage/coverage.xml"

[tool.coverage.run]
omit = [
    "tests/*",
    ]

[tool.black]
include = '\.py$'
line-length = 79

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
